### ISSUE TITLE
It's really perfect if support soft mask effect like "SoftMaskForUGUI"

### ISSUE THREAD

**Issue by daneric** [mob-sakai/UnmaskForUGUI#12]
I also use the "SoftMaskForUGUI" plugin. That's perfect effect except Inverse SoftMaskable must be the child of SoftMask in Hierarchy. I cannot make multiple holes on one background. 
Then I found this plugin "UnmaskForUGUI". It allows me to make multiple holes on one background, but without soft mask effect. Is it possible to use soft mask to make multiple holes on one background?
Thanks for sharing your plugins! Both of them are very useful for me.

**Comment by mob-sakai** [comment]
Hi @daneric 
Thank you for using UnmaskForUGUI and SoftMaskForUGUI.
I understand what you mean.
However, UnmaskForUGUI uses stencil, so it is impossible to use a soft mask...

I added this feature request to SoftMaskForUGUI.
https://github.com/mob-sakai/SoftMaskForUGUI/issues/29

**Comment by daneric** [comment]
Thanks for reply! @mob-sakai 
I am looking forward!
Best Wishes!
