### ISSUE TITLE
Can't install package using UPM

### ISSUE THREAD

**Issue by caneva20** [mob-sakai/UnmaskForUGUI#15]
The package can't be installed using Unity package manager (UPM)

`'5.5' is not valid 'unity' attribute value. Expected '<year>.<version>'`

**To Reproduce**
1. Go to Packages/manifest.json
2. Add the following line: 
`"com.coffee.unmask": "https://github.com/mob-sakai/UnmaskForUGUI.git#1.1.1",`

**Environment:**
 - Platform: Editor Windows
 - Unity: 2019.1.4f1
 - UnmaskForUGUI: 1.1.1

**Comment by mob-sakai** [comment]
Hi @caneva20 
Thank you for reporting.
I will fix it ASAP.

**Comment by mob-sakai** [comment]
1.1.2 is installable, but that doesn't work.
