### ISSUE TITLE
The ray Passes through the unmasked rectangle. Not work for Canvas render mode :Screen Space -Camera

### ISSUE THREAD

**Issue by mcaisw** [mob-sakai/UnmaskForUGUI#19]
In my case ,my canvas was setting to Screen Space -camera,and then,the UnmaskRaycastFilter componet didn't work,The ray can not Passes through the unmasked rectangle.

**Environment (please complete the following information):**
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity: [e.g. 2018.4.0f1]
 - UnmaskForUGUI: [e.g. v1.0.0]

**Comment by harunuysali07** [comment]
Same here, you can user Screep Space - Overlay for an alternative

**Comment by mob-sakai** [comment]
Hi @mcaisw @harunuysali07 

Thank you for your reporting!

**Comment by drlevy** [comment]
I also ran into this issue recently when attempting to add 3D VFX to a 2D UI. 

If you switched to "Screen Space - Camera" for a similar use case, you can instead use "Overlay" in conjunction with another awesome package from @mob-sakai (see: https://github.com/mob-sakai/ParticleEffectForUGUI).

**Comment by mob-sakai** [comment]
This issue will be fixed in next version!

**Comment by T--T** [comment]
add a parameter on the RectTransformUtility.RectangleContainsScreenPoint()  can fix this problem

UnmaskRaycastFilter.cs -> public bool IsRaycastLocationValid(Vector2 sp, Camera eventCamera)

> return !RectTransformUtility.RectangleContainsScreenPoint((m_TargetUnmask.transform as RectTransform), sp, _**eventCamera**_);

**Comment by T--T** [comment]
But it's still not right in release v1.1.3 @mob-sakai

**Comment by mob-sakai** [comment]
@T--T 

Thank you for your information!

**Comment by alex-turantsev** [comment]
@mob-sakai Can you make upm version with this fix, please?

**Comment by mob-sakai** [comment]
@T--T @alex-turantsev 
Sorry!

**Comment by mob-sakai** [comment]
Fixed in v1.2.0.

**Comment by riqmariz** [comment]
For me, is not working T--T, any thoughts? I tried to use something like the demo tutorial button the package has, but not works for me. I use the same canvas as mentioned above. Unity 2019.4.11f1, using new input, I don't if related.
