### ISSUE TITLE
Softmask with alpha support?

### ISSUE THREAD

**Issue by hlongvu** [mob-sakai/UnmaskForUGUI#20]
I've been using your library and it's great.
But I notice that the mask's border will be pixelated when using sprite with alpha color. Could it support soft mask like SoftMaskForUGUI?

**Comment by mob-sakai** [comment]
Hi @hlongvu 

I would like to know more information on this issue.
Can you attach a minimal repro project or a screenshot for this issue?

**Comment by hlongvu** [comment]
Hi, this is screenshot of my setup. You can see I am using the hightlight_1 image with fading border. I want to make the hole in my panel fading from transparent into dark. But the mask is showing pixelated border.

[Imgur](https://imgur.com/1NvZV9c)

**Comment by mob-sakai** [comment]
Okay, please attach hightlight_1.

**Comment by mob-sakai** [comment]
Try using clamp instead of repeat in the image import settings.

**Comment by hlongvu** [comment]
This is the project zip file [Google Drive Link] (https://drive.google.com/file/d/16hsWmror8dKz7wxkZbexuP4WSv5hYLvb/view?usp=sharing)
And the image here [Imgur](https://imgur.com/Qhgauj1)
I tried using clamp in import settings but nothing changes.

**Comment by mob-sakai** [comment]
Oh, sorry, I was misunderstood.
UnmaskForUGUI does not support smooth masks.
You can use [SoftMaskForUGUI](https://github.com/mob-sakai/SoftMaskForUGUI).
It support **invert masking.**
![](https://user-images.githubusercontent.com/12690315/48708328-a0d4cf80-ec45-11e8-9945-e877faabc968.png)

**Comment by hlongvu** [comment]
Thank you, I will try SoftMaskForUGUI.
This library has nice feature like fit target and raycast filter, hope you will add support for SoftMask.
