### ISSUE TITLE
how to make the edge of hole blur？

### ISSUE THREAD

**Issue by mcaisw** [mob-sakai/UnmaskForUGUI#22]
I cut a hole on a black image,but the hole's edge  looks like  too sharp,so ,how to blur the edge of the hole?
<img width="728" alt="WeChat4c233a52be708c88327b03bffed0bbfe" src="https://user-images.githubusercontent.com/21421885/71447771-b3d1a180-276d-11ea-8d93-e41c8dc43b3b.png">

**Comment by mob-sakai** [comment]
Hi @mcaisw 

I have 2 solutions.

## Solution 1: Use [SoftMaskForUGUI](https://github.com/mob-sakai/SoftMaskForUGUI)

Use `Inverse` option.
Usage differs from this package.

## Solution 2: Use fake alpha transparency with dithering

https://forum.unity.com/threads/shader-graph-alpha-clip-dither-but-retain-shadows.607384/
