### ISSUE TITLE
Only for children option inside a scrollview

### ISSUE THREAD

**Issue by Racines** [mob-sakai/UnmaskForUGUI#24]
Hello,

I want to use Unmask with the option "only for children" inside a scrollview (the viewport use the default UI mask).
When I do this, the mask of the viewport do not affect anymore the children that are ordered after the Unmask gameobject.
![image](https://user-images.githubusercontent.com/31736912/118467437-13827100-b704-11eb-98a5-d223f4183afe.png)

My hierarchy:
![image](https://user-images.githubusercontent.com/31736912/118467631-40cf1f00-b704-11eb-803e-775f2be55a55.png)

ShadowMask use Unmask with "only for children" option
and Viewport use default UI mask

Am I doing something wrong? or this is a bug?
(in this example I could manage to avoid using "only for children" but in my project I can't)

**Comment by mob-sakai** [comment]
@Racines 
Sorry for my late reply.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by Racines** [comment]
@mob-sakai 
I made a simple project, you can open the Bug scene to view the issue.
[UnmaskForUGUIBugMinimal.zip](https://github.com/mob-sakai/UnmaskForUGUI/files/6725622/UnmaskForUGUIBugMinimal.zip)

**Comment by mob-sakai** [comment]
@Racines 
Thanks a lot!

**Comment by mob-sakai** [comment]
WIP
![](https://user-images.githubusercontent.com/12690315/123769834-a9650a80-d904-11eb-90fe-5f044f73ceed.png)

**Comment by Racines** [comment]
> WIP
> ![](https://user-images.githubusercontent.com/12690315/123769834-a9650a80-d904-11eb-90fe-5f044f73ceed.png)

Nice :)
