### ISSUE TITLE
Unmask is not working if not child of a Unity Mask

### ISSUE THREAD

**Issue by Racines** [mob-sakai/UnmaskForUGUI#25]
Hello,

I noticed that Unmask is not working if not child of a Unity Mask.
![image](https://user-images.githubusercontent.com/31736912/128489389-50beeac4-cddf-42dd-a588-294a77c70836.png)

I made a simple project, you can open the Bug scene to view the issue.
[UnmaskForUGUIBugUnmask.zip](https://github.com/mob-sakai/UnmaskForUGUI/files/6944585/UnmaskForUGUIBugUnmask.zip)

The shadow of ElementTemplateOutside is still visible in the center.
I use the v1.3 of UnmaskForUGUI

**Comment by mob-sakai** [comment]
No, It is **by design.**
`Unmask` will only work if it is under `Mask`.
