### ISSUE TITLE
How to create zone that allows everything in its range to be clickable?

### ISSUE THREAD

**Issue by Tetromiko** [mob-sakai/UnmaskForUGUI#30]
I am creating highlight zone for FTUE and don't understand how to make screen covered with shadow with bright spot that can be manipulated to guide our player to click certain buttons or something else, but take away the ability to click within zone's range. I've tried
![image](https://github.com/user-attachments/assets/6fd5586c-a176-4de7-83df-792222664d93)
![image](https://github.com/user-attachments/assets/53d89e46-1337-4916-8136-78f2bf2434c8)
![image](https://github.com/user-attachments/assets/12610d4e-0263-4dca-a349-6aca890100d3)
![image](https://github.com/user-attachments/assets/87da82bd-534a-4497-aa2d-f6b0c2555e39)

**Comment by mob-sakai** [comment]
1. This is a different repository. Please create a new issue here.
https://github.com/mob-sakai/SoftMaskForUGUI/issues/new?assignees=mob-sakai&labels=question&projects=&template=question.md&title=

2. Tell me about your develop/build environment.
   - SoftMaskForUGUI version [e.g. 3.0.0]
   - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
   - Unity version: [e.g. 2022.2.0f1]
   - Build options: [e.g. IL2CPP, .Net 4.x, URP/HDRP]

3. Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.  
   ![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)
